// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ85JrCpbiHkkVtUxbLxWEnJB4heSqv8Y',
    appId: '1:760200443173:web:b2188a9b499624297e16cc',
    messagingSenderId: '760200443173',
    projectId: 'pointyourfood-jstudios',
    authDomain: 'pointyourfood-jstudios.firebaseapp.com',
    storageBucket: 'pointyourfood-jstudios.appspot.com',
    measurementId: 'G-TCHQG79ZQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAWcrRX_6YrLiH86iOqNzcAO9NzGcySb8',
    appId: '1:760200443173:android:0fc21a9129e3335b7e16cc',
    messagingSenderId: '760200443173',
    projectId: 'pointyourfood-jstudios',
    storageBucket: 'pointyourfood-jstudios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrIrnuF9kg3B5MPUIBJdljdZt0u-VBV-8',
    appId: '1:760200443173:ios:c55b8bd0467c312b7e16cc',
    messagingSenderId: '760200443173',
    projectId: 'pointyourfood-jstudios',
    storageBucket: 'pointyourfood-jstudios.appspot.com',
    iosClientId: '760200443173-0g3r9ag7davjdj97pe4t6ts1j2s14vbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.punkteZaehler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrIrnuF9kg3B5MPUIBJdljdZt0u-VBV-8',
    appId: '1:760200443173:ios:c55b8bd0467c312b7e16cc',
    messagingSenderId: '760200443173',
    projectId: 'pointyourfood-jstudios',
    storageBucket: 'pointyourfood-jstudios.appspot.com',
    iosClientId: '760200443173-0g3r9ag7davjdj97pe4t6ts1j2s14vbh.apps.googleusercontent.com',
    iosBundleId: 'com.example.punkteZaehler',
  );
}
